servers:
  web:
    hosts:
      - 192.210.167.222

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# If using something like Cloudflare, it is recommended to set encryption mode 
# in Cloudflare's SSL/TLS setting to "Full" to enable end-to-end encryption. 
proxy: 
  host: staging.sprintosaurus.com
  ssl: true
